### ISSUE TITLE
please support password usage. In the update to 2.0-RC its not accessable by Java (no Kotlin)

### ISSUE THREAD

**Issue by Alf21** [Shoebill/shoebill-common#4]
https://github.com/Shoebill/shoebill-common/blob/d4070219c8729755cf2a36910a1a1b1302c25ff8/src/main/java/net/gtaun/shoebill/common/dialog/InputDialog.kt#L103

**Comment by 123marvin123** [comment]
Changed in cb136033083c1d3053c30684076bf1ae9049daa2
